In [1]:
import pandas as pd
import numpy as np
import tqdm as tqdm

In [2]:
dataframe = pd.read_pickle('reduced.pickle')
#pre processing missing values of prices by transforming with mean price of that id
dataframe['sell_price'].fillna(dataframe.groupby('id')['sell_price'].transform('mean'),inplace=True)
dataframe.head(100)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,8.281250
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,3.970703
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,2.970703
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,4.523438
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,2.943359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,HOBBIES_1_099_CA_1_validation,HOBBIES_1_099_CA_1_validation,HOBBIES_1_099_CA_1_validation,HOBBIES_1_099_CA_1_validation,HOBBIES_1_099_CA_1_validation,HOBBIES_1_099_CA_1_validation,1,2,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,14.257812
96,HOBBIES_1_100_CA_1_validation,HOBBIES_1_100_CA_1_validation,HOBBIES_1_100_CA_1_validation,HOBBIES_1_100_CA_1_validation,HOBBIES_1_100_CA_1_validation,HOBBIES_1_100_CA_1_validation,1,1,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,10.000000
97,HOBBIES_1_102_CA_1_validation,HOBBIES_1_102_CA_1_validation,HOBBIES_1_102_CA_1_validation,HOBBIES_1_102_CA_1_validation,HOBBIES_1_102_CA_1_validation,HOBBIES_1_102_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,4.980469
98,HOBBIES_1_103_CA_1_validation,HOBBIES_1_103_CA_1_validation,HOBBIES_1_103_CA_1_validation,HOBBIES_1_103_CA_1_validation,HOBBIES_1_103_CA_1_validation,HOBBIES_1_103_CA_1_validation,1,25,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,0.700195
99,HOBBIES_1_104_CA_1_validation,HOBBIES_1_104_CA_1_validation,HOBBIES_1_104_CA_1_validation,HOBBIES_1_104_CA_1_validation,HOBBIES_1_104_CA_1_validation,HOBBIES_1_104_CA_1_validation,1,0,2011-01-29,11101,...,1,59,NaN,NaN,NaN,NaN,0,0,0,23.984375

In [3]:
#insert lag features to 'dataframe'
shifting = 28
for i in range(9): #num of weeks to shift here 8 weeks we consider
    dataframe['lag_'+str(shifting+(7*i))] = dataframe.groupby('id')['sales'].shift(shifting+(7*i)).astype(np.float16)

In [6]:
dataframe.tail(100)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,sell_price,lag_28,lag_35,lag_42,lag_49,lag_56,lag_63,lag_70,lag_77,lag_84
58327270,FOODS_3_726_WI_3_validation,FOODS_3_726_WI_3_validation,FOODS_3_726_WI_3_validation,FOODS_3_726_WI_3_validation,FOODS_3_726_WI_3_validation,FOODS_3_726_WI_3_validation,1913,1,2016-04-24,11613,...,2.560547,4.0,1.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0
58327271,FOODS_3_727_WI_3_validation,FOODS_3_727_WI_3_validation,FOODS_3_727_WI_3_validation,FOODS_3_727_WI_3_validation,FOODS_3_727_WI_3_validation,FOODS_3_727_WI_3_validation,1913,5,2016-04-24,11613,...,3.980469,9.0,6.0,7.0,10.0,6.0,3.0,5.0,9.0,8.0
58327272,FOODS_3_729_WI_3_validation,FOODS_3_729_WI_3_validation,FOODS_3_729_WI_3_validation,FOODS_3_729_WI_3_validation,FOODS_3_729_WI_3_validation,FOODS_3_729_WI_3_validation,1913,1,2016-04-24,11613,...,3.980469,1.0,4.0,3.0,1.0,3.0,2.0,1.0,1.0,1.0
58327273,FOODS_3_730_WI_3_validation,FOODS_3_730_WI_3_validation,FOODS_3_730_WI_3_validation,FOODS_3_730_WI_3_validation,FOODS_3_730_WI_3_validation,FOODS_3_730_WI_3_validation,1913,3,2016-04-24,11613,...,4.980469,1.0,1.0,0.0,1.0,1.0,1.0,3.0,1.0,0.0
58327274,FOODS_3_731_WI_3_validation,FOODS_3_731_WI_3_validation,FOODS_3_731_WI_3_validation,FOODS_3_731_WI_3_validation,FOODS_3_731_WI_3_validation,FOODS_3_731_WI_3_validation,1913,2,2016-04-24,11613,...,2.980469,2.0,2.0,0.0,0.0,0.0,3.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58327365,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,1913,1,2016-04-24,11613,...,2.980469,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0
58327366,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,1913,0,2016-04-24,11613,...,2.480469,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58327367,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,1913,0,2016-04-24,11613,...,3.980469,1.0,0.0,1.0,2.0,0.0,0.0,1.0,1.0,2.0
58327368,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,1913,3,2016-04-24,11613,...,1.280273,4.0,1.0,3.0,2.0,0.0,0.0,2.0,1.0,3.0
58327369,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,1913,0,2016-04-24,11613,...,1.000000,5.0,4.0,4.0,0.0,0.0,2.0,1.0,2.0,1.0

In [7]:
#insert rolling features 'dataframe'
for i in [7,14,28,35,60]:
    dataframe['rolling_mean_'+str(i)] =  dataframe.groupby(['id'])['lag_28'].transform(lambda x: x.rolling(i).mean())
    dataframe['rolling_median_'+str(i)] =  dataframe.groupby(['id'])['lag_28'].transform(lambda x: x.rolling(i).median())

In [5]:
dataframe.tail(1000)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,rolling_mean_7,rolling_median_7,rolling_mean_14,rolling_median_14,rolling_mean_28,rolling_median_28,rolling_mean_35,rolling_median_35,rolling_mean_60,rolling_median_60
58326370,FOODS_2_223_WI_3_validation,FOODS_2_223_WI_3_validation,FOODS_2_223_WI_3_validation,FOODS_2_223_WI_3_validation,FOODS_2_223_WI_3_validation,FOODS_2_223_WI_3_validation,1913,0,2016-04-24,11613,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.016667,0.0
58326371,FOODS_2_224_WI_3_validation,FOODS_2_224_WI_3_validation,FOODS_2_224_WI_3_validation,FOODS_2_224_WI_3_validation,FOODS_2_224_WI_3_validation,FOODS_2_224_WI_3_validation,1913,0,2016-04-24,11613,...,0.285714,0.0,0.428571,0.0,0.607143,0.0,0.657143,0.0,0.666667,0.0
58326372,FOODS_2_225_WI_3_validation,FOODS_2_225_WI_3_validation,FOODS_2_225_WI_3_validation,FOODS_2_225_WI_3_validation,FOODS_2_225_WI_3_validation,FOODS_2_225_WI_3_validation,1913,2,2016-04-24,11613,...,1.428571,1.0,1.714286,1.0,1.392857,1.0,1.257143,1.0,1.366667,1.0
58326373,FOODS_2_226_WI_3_validation,FOODS_2_226_WI_3_validation,FOODS_2_226_WI_3_validation,FOODS_2_226_WI_3_validation,FOODS_2_226_WI_3_validation,FOODS_2_226_WI_3_validation,1913,1,2016-04-24,11613,...,0.000000,0.0,0.000000,0.0,0.178571,0.0,0.142857,0.0,0.150000,0.0
58326374,FOODS_2_227_WI_3_validation,FOODS_2_227_WI_3_validation,FOODS_2_227_WI_3_validation,FOODS_2_227_WI_3_validation,FOODS_2_227_WI_3_validation,FOODS_2_227_WI_3_validation,1913,2,2016-04-24,11613,...,1.285714,1.0,1.285714,1.0,1.392857,1.0,1.428571,1.0,1.516667,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58327365,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,FOODS_3_823_WI_3_validation,1913,1,2016-04-24,11613,...,0.000000,0.0,0.000000,0.0,0.250000,0.0,0.257143,0.0,0.500000,0.0
58327366,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,FOODS_3_824_WI_3_validation,1913,0,2016-04-24,11613,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
58327367,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,FOODS_3_825_WI_3_validation,1913,0,2016-04-24,11613,...,0.714286,0.0,0.857143,0.5,1.250000,1.0,1.085714,1.0,0.933333,1.0
58327368,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,FOODS_3_826_WI_3_validation,1913,3,2016-04-24,11613,...,1.571429,1.0,1.357143,1.0,1.250000,1.0,1.000000,1.0,1.100000,1.0
58327369,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,FOODS_3_827_WI_3_validation,1913,0,2016-04-24,11613,...,2.428571,2.0,2.285714,2.5,1.964286,2.0,1.828571,2.0,1.850000,1.5

In [6]:
#reduce size of lag/rolling features
dataframe.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58327370 entries, 0 to 58327369
Data columns (total 41 columns):
 #   Column             Dtype
---  ------             -----
 0   id                 category
 1   item_id            category
 2   dept_id            category
 3   cat_id             category
 4   store_id           category
 5   state_id           category
 6   d                  int16
 7   sales              int16
 8   date               datetime64[ns]
 9   wm_yr_wk           int16
 10  weekday            category
 11  wday               int8
 12  month              int8
 13  year               int8
 14  event_name_1       category
 15  event_type_1       category
 16  event_name_2       category
 17  event_type_2       category
 18  snap_CA            category
 19  snap_TX            category
 20  snap_WI            category
 21  sell_price         float16
 22  lag_28             float16
 23  lag_35             float16
 24  lag_42             float16
 25  lag_49             float16
 26  lag_56             float16
 27  lag_63             float16
 28  lag_70             float16
 29  lag_77             float16
 30  lag_84             float16
 31  rolling_mean_7     float64
 32  rolling_median_7   float64
 33  rolling_mean_14    float64
 34  rolling_median_14  float64
 35  rolling_mean_28    float64
 36  rolling_median_28  float64
 37  rolling_mean_35    float64
 38  rolling_median_35  float64
 39  rolling_mean_60    float64
 40  rolling_median_60  float64
dtypes: category(14), datetime64[ns](1), float16(10), float64(10), int16(3), int8(3)
memory usage: 7.5 GB

In [7]:
for col in dataframe.columns[-10:]:
    print(dataframe[col].max())
    
for col in dataframe.columns[-10:]:
    print(dataframe[col].min())

602.8571428571429
613.0
468.64285714285717
454.5
442.75
454.0
413.14285714285717
357.0
310.18333333333334
289.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [8]:
dataframe['rolling_mean_7'] = dataframe['rolling_mean_7'].astype('float16')
dataframe['rolling_mean_14'] = dataframe['rolling_mean_14'].astype('float16')
dataframe['rolling_mean_28'] = dataframe['rolling_mean_28'].astype('float16')
dataframe['rolling_mean_35'] = dataframe['rolling_mean_35'].astype('float16')
dataframe['rolling_mean_60'] = dataframe['rolling_mean_60'].astype('float16')
dataframe['rolling_median_7'] = dataframe['rolling_median_7'].astype('float16')
dataframe['rolling_median_14'] = dataframe['rolling_median_14'].astype('float16')
dataframe['rolling_median_28'] = dataframe['rolling_median_28'].astype('float16')
dataframe['rolling_median_35'] = dataframe['rolling_median_35'].astype('float16')
dataframe['rolling_median_60'] = dataframe['rolling_median_60'].astype('float16')

In [9]:
for col in dataframe.columns[-10:]:
    print(dataframe[col].max())
    
for col in dataframe.columns[-10:]:
    print(dataframe[col].min())

603.0
613.0
468.8
454.5
442.8
454.0
413.2
357.0
310.2
289.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [10]:
dataframe.to_pickle('preprocessed.pickle')